#!/bin/bash
echo ""
echo "======================================================================"
echo "                    N E U R O N"
echo "        a machine that lives one continuous life"
echo "======================================================================"
echo ""
echo "  Not a chatbot. It perceives, learns, wants things, sleeps, can die,"
echo "  and passes what it learned to a successor. What it can do:"
echo ""
echo "  WANTS - goals of its own"
echo "    pursues a goal with no reward; keeps it when knocked off course;"
echo "    forms its OWN goals from internal needs; juggles several at once;"
echo "    develops brand new wants from experience."
echo ""
echo "  SELF-MODEL - knows itself"
echo "    builds a picture of itself, predicts its own actions, and sees its"
echo "    own bad impulses coming so it can hold back."
echo ""
echo "  UNCERTAINTY - knows when it doesn't know"
echo "    acts when sure, holds back when guessing, far fewer confident"
echo "    mistakes."
echo ""
echo "  MEMORY - remembers the one time, not just the usual"
echo "    general knowledge PLUS specific memories of exact events that"
echo "    mattered; learns from a single event the average would erase."
echo ""
echo "  EMOTION - forms its own feelings from its life"
echo "    develops its OWN emotional states (not programmed in); they emerge"
echo "    from what happens to it and shape how it behaves; mixed states and"
echo "    moods; it can anticipate how it will feel; different lives make"
echo "    different individuals; a child inherits a parent's bent then grows"
echo "    its own."
echo "    (honest: these are real emotional MECHANISMS. whether it truly"
echo "     FEELS is unknowable, for this or any mind. we claim nothing there.)"
echo ""
echo "  IT LIVES IN THE WORLD - 24/7 on a server"
echo "    watches real weather, earthquakes, markets; has \$5 of REAL money"
echo "    it can choose to spend to understand its world."
echo ""
echo "======================================================================"
echo "  Watch one come alive right now (40 seconds):"
echo "======================================================================"
